query getCollectionProducts($handleName: String!, $cursor: String) {
  collectionByHandle(handle: $handleName) {
    title
    image {
      originalSrc
    }
    products(first: 20, after: $cursor, sortKey: CREATED, reverse: true) {
      edges {
        cursor
        node {
          collections(first: 3) {
            edges {
              node {
                title
                handle
              }
            }
          }
          title
          handle
          tags
          images(first: 1) {
            edges {
              node {
                originalSrc
              }
            }
          }
          onlineStoreUrl
          priceRange {
            maxVariantPrice {
              amount
            }
            minVariantPrice {
              amount
            }
          }
          totalInventory
          id
        }
      }
    }
  }
}
